name: Run Main

on:
  push:
    branches:
      - lab4
  pull_request:
    branches:
      - lab4

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run Part1 tasks
        run: |
          python part1/task1.py
          python part1/task2.py
          python part1/task3.py
          python part1/task4.py
          python part1/task5.py
          python part1/task6.py

      - name: Run Part2 tasks
        run: |
          python part2/task1.py
          python part2/task2.py
          python part2/task3.py
          python part2/task4.py
