name: Run Main

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Miniconda
        run: |
          # Установка Miniconda
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          conda init bash
          source $HOME/miniconda/etc/profile.d/conda.sh

      - name: Create environment
        run: |
          conda env create -f setup.yml 
          conda activate myenv            

      - name: Run main.py
        run: |
          cd main                     
          python test.py              
