name: Run Main

on:
  push:
    branches:
      - lab3
  pull_request:
    branches:
      - lab3

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py
