name: Run Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout lab1 branch
        uses: actions/checkout@v2
       
